### ISSUE TITLE
用gunicorn部署问题

### ISSUE THREAD

**Issue by juventusryp** [greyli/sayhello#10]
您好，最近看书部署部分，用gunicorn想部署下sayhello程序实验。

在sayhello目录下运行`gunicorn sayhello:app`可以正常

但是在sayhello/sayhello下运行`gunicorn __init__:app` 提示如下

```
[2019-03-23 22:52:35 +0800] [73809] [INFO] Starting gunicorn 19.9.0
[2019-03-23 22:52:35 +0800] [73809] [INFO] Listening at: http://127.0.0.1:8000 (73809)
[2019-03-23 22:52:35 +0800] [73809] [INFO] Using worker: sync
[2019-03-23 22:52:35 +0800] [73812] [INFO] Booting worker with pid: 73812
[2019-03-23 22:52:35 +0800] [73812] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/lovehxy/Downloads/sayhello/sayhello/__init__.py", line 14, in <module>
    app.config.from_pyfile('settings.py')
  File "/usr/local/lib/python3.7/site-packages/flask/config.py", line 130, in from_pyfile
    exec(compile(config_file.read(), filename, 'exec'), d.__dict__)
  File "/Users/lovehxy/Downloads/sayhello/sayhello/settings.py", line 11, in <module>
    from sayhello import app
ModuleNotFoundError: No module named 'sayhello'
[2019-03-23 22:52:35 +0800] [73812] [INFO] Worker exiting (pid: 73812)
[2019-03-23 22:52:35 +0800] [73809] [INFO] Shutting down: Master
[2019-03-23 22:52:35 +0800] [73809] [INFO] Reason: Worker failed to boot.
```

请教原因？

**Comment by greyli** [comment]
看起来和 Gunicorn 导入的方式有关。不过你完全没有必要切换到包目录，只需要在项目根目录启动 Gunicorn 即可。

**Comment by juventusryp** [comment]
是的 已经解决，在项目根目录下执行即可，谢谢！关闭了
