### ISSUE TITLE
直接clone下代码，在pycharm运行项目的时候，就报了错误，会不会是环境配置的问题，，从邮件那篇开始就总有traceback

### ISSUE THREAD

**Issue by 99Kies** [greyli/sayhello#17]
C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\Scripts\python.exe C:/Users/DELL/Desktop/say_hello/sayhello/test_sayhello.py
....EFFEE..
======================================================================
ERROR: test_create_message (__main__.SayHelloTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/say_hello/sayhello/test_sayhello.py", line 67, in test_create_message
    ), follow_redirects=True)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 1039, in post
    return self.open(*args, **kw)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\testing.py", line 227, in open
    follow_redirects=follow_redirects,
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 1017, in open
    response, new_location, environ, buffered=buffered
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 948, in resolve_redirect
    return self.open(builder, as_tuple=True, buffered=buffered)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\testing.py", line 227, in open
    follow_redirects=follow_redirects,
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 993, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 884, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\DELL\Desktop\say_hello\sayhello\sayhello\views.py", line 28, in index
    return render_template('index.html', form=form, messages=messages)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\DELL\Desktop\say_hello\sayhello\sayhello\templates\index.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form %}
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/form.html

======================================================================
ERROR: test_form_validation (__main__.SayHelloTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/say_hello/sayhello/test_sayhello.py", line 76, in test_form_validation
    ), follow_redirects=True)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 1039, in post
    return self.open(*args, **kw)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\testing.py", line 227, in open
    follow_redirects=follow_redirects,
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 993, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 884, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\DELL\Desktop\say_hello\sayhello\sayhello\views.py", line 28, in index
    return render_template('index.html', form=form, messages=messages)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\DELL\Desktop\say_hello\sayhello\sayhello\templates\index.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form %}
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/form.html

======================================================================
ERROR: test_index_page (__main__.SayHelloTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/say_hello/sayhello/test_sayhello.py", line 59, in test_index_page
    response = self.client.get('/')
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 1029, in get
    return self.open(*args, **kw)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\testing.py", line 227, in open
    follow_redirects=follow_redirects,
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 993, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 884, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\werkzeug\test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\DELL\Desktop\say_hello\sayhello\sayhello\views.py", line 28, in index
    return render_template('index.html', form=form, messages=messages)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\DELL\Desktop\say_hello\sayhello\sayhello\templates\index.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form %}
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\DELL\.virtualenvs\flasky-k2ovOsk9\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/form.html

======================================================================
FAIL: test_forge_command (__main__.SayHelloTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/say_hello/sayhello/test_sayhello.py", line 82, in test_forge_command
    self.assertIn('Created 20 fake messages.', result.output)
AssertionError: 'Created 20 fake messages.' not found in ''

======================================================================
FAIL: test_forge_command_with_count (__main__.SayHelloTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/say_hello/sayhello/test_sayhello.py", line 87, in test_forge_command_with_count
    self.assertIn('Created 50 fake messages.', result.output)
AssertionError: 'Created 50 fake messages.' not found in ''

----------------------------------------------------------------------
Ran 11 tests in 0.057s

FAILED (failures=2, errors=3)

Process finished with exit code 1

**Comment by luwanglin** [comment]
jinja2.exceptions.TemplateNotFound: bootstrap/form.html 应该是这个问题

**Comment by greyli** [comment]
需要确保安装了依赖 Bootstrap-Flask：
```bash
$ pip install bootstrap-flask
```
