### ISSUE TITLE
pipenv install --dev 执行之后 所有的包不能安装         请问这是什么原因呢 

### ISSUE THREAD

**Issue by aa31** [greyli/sayhello#2]
一直都是按照教程走的
python 3.4  windows10  
clone下来  进入项目 安装依赖的时候就这样  
pip  18     pipenv v2018.7.1

Administrator@88DPIN40VXPT4MR MINGW64 /c/ENV/pro/sayhello (master)
$ pipenv install --dev --pypi-mirror https://mirrors.aliyun.com/pypi/simple
Installing dependencies from Pipfile.lock (b158df)...
An error occurred while installing argh==0.26.2! Will try again.
An error occurred while installing ipaddress==1.0.22; python_version == '2.7'! Will try again.
An error occurred while installing text-unidecode==1.2! Will try again.
An error occurred while installing faker==0.8.17! Will try again.
An error occurred while installing six==1.11.0! Will try again.
An error occurred while installing python-dateutil==2.7.3! Will try again.
An error occurred while installing pathtools==0.1.2! Will try again.
An error occurred while installing watchdog==0.8.3! Will try again.
An error occurred while installing pyyaml==3.13! Will try again.
An error occurred while installing python-dotenv==0.8.2! Will try again.
An error occurred while installing itsdangerous==0.24! Will try again.
An error occurred while installing flask-wtf==0.14.2! Will try again.
An error occurred while installing click==6.7! Will try again.
An error occurred while installing jinja2==2.10! Will try again.
An error occurred while installing flask==1.0.2! Will try again.

Could not import runpy module
ModuleNotFoundError: No module named 'runpy'

**Comment by greyli** [comment]
有可能是Python环境的问题，可以重装一下Python试试

**Comment by mylysddp** [comment]
pipenv install --dev   也是遇到同样的问题，一直提示module object is not callable，没办法，后面只能直接export 指定应用名

**Comment by greyli** [comment]
@mylysddp 麻烦提供一下完整的错误信息和pipenv、pip、Python的版本

**Comment by mylysddp** [comment]
pipenv  2018.7.1      pip 18.1   python 3.6
报错信息如下：
`pipenv install --dev
Installing dependencies from Pipfile.lock (b158df)...
Traceback (most recent call last):▉▉▉▉▉ 0/22 — 00:00:00
  File "/anaconda3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
`

**Comment by mylysddp** [comment]
pipenv 2018.7.1 pip 18.1 python 3.6
报错信息如下：
Installing dependencies from Pipfile.lock (b158df)...
Traceback (most recent call last):▉▉▉▉▉ 0/22 — 00:00:00
  File "/anaconda3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/anaconda3/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/22 — 00:00:00

**Comment by greyli** [comment]
这个是pipenv的bug，你可以试一下把pipenv升级到最新版本：
```
$ pip install -U pipenv
```

**Comment by mylysddp** [comment]
> 这个是pipenv的bug，你可以试一下把pipenv升级到最新版本：
> 
> ```
> $ pip install -U pipenv
> ```

升级后可以了，谢谢！
